"""
LLM-Enhanced Threat Analyzer

Uses HuggingFace Router with gpt-oss-20b:groq for AI-assisted threat detection,
complementing the rule-based knowledge graph approach.
"""
import os
import json
from typing import List, Dict, Optional
from dataclasses import dataclass
import networkx as nx
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

try:
    from openai import OpenAI
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False


@dataclass
class LLMThreatFinding:
    """Threat finding generated by LLM analysis."""
    threat_id: str
    component: str
    severity: str
    description: str
    attack_vector: str
    mitigation: str
    cwe_references: List[str] = None


class LLMThreatAnalyzer:
    """
    LLM-powered threat analyzer using HuggingFace Router with gpt-oss-20b:groq.
    
    This provides a complementary analysis to the knowledge graph, offering:
    - Natural language understanding of complex patterns
    - Contextual reasoning about threat scenarios
    - Novel threat identification beyond predefined rules
    """
    
    def __init__(self, api_key: Optional[str] = None):
        if not OPENAI_AVAILABLE:
            raise ImportError("OpenAI package not installed. Run: pip install openai")
        
        self.api_key = api_key or os.getenv("HF_TOKEN")
        if not self.api_key:
            raise ValueError(
                "HuggingFace token required. Create a .env file with: HF_TOKEN=hf_..."
            )
        
        self.client = OpenAI(
            base_url="https://router.huggingface.co/v1",
            api_key=self.api_key
        )
        self.model = "openai/gpt-oss-20b:groq"
    
    def analyze_architecture(self, graph: nx.DiGraph, typespec_source: str = None) -> List[LLMThreatFinding]:
        """
        Analyze architecture using LLM reasoning.
        
        Args:
            graph: Property graph representing the architecture
            typespec_source: Optional TypeSpec source for richer context
        
        Returns:
            List of LLM-identified threats
        """
        # Serialize graph to structured JSON for LLM
        arch_description = self._graph_to_description(graph)
        
        # Build prompt for threat analysis
        prompt = self._build_threat_analysis_prompt(arch_description, typespec_source)
        
        # Query LLM
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a Senior Enterprise Architect specializing in threat modeling "
                            "for AI/ML systems, particularly RAG (Retrieval-Augmented Generation) "
                            "architectures. You understand STRIDE, OWASP Top 10, and AI-specific "
                            "threats like prompt injection, model inversion, and data poisoning."
                        )
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.0,
                response_format={"type": "json_object"}
            )
            
            # Parse LLM response
            findings = self._parse_llm_response(response.choices[0].message.content)
            return self._filter_verifiable_findings(findings, graph)
            
        except Exception as e:
            print(f"LLM analysis failed: {e}")
            return []

    def _filter_verifiable_findings(
        self, findings: List[LLMThreatFinding], graph: nx.DiGraph
    ) -> List[LLMThreatFinding]:
        """Filter findings down to those that satisfy explicit, machine-checkable constraints."""
        allowed_severity = {"Critical", "High", "Medium", "Low"}
        kept: List[LLMThreatFinding] = []

        for f in findings:
            if not f.threat_id or not isinstance(f.threat_id, str):
                continue
            if not f.component or not isinstance(f.component, str):
                continue
            if f.component not in graph.nodes:
                continue
            if f.severity not in allowed_severity:
                continue
            if not f.description or not isinstance(f.description, str):
                continue
            if not f.mitigation or not isinstance(f.mitigation, str):
                continue
            kept.append(f)

        dropped = len(findings) - len(kept)
        if dropped:
            print(f"LLM findings filtered: dropped {dropped} non-verifiable item(s)")
        return kept
    
    def _graph_to_description(self, graph: nx.DiGraph) -> Dict:
        """Convert graph to structured description for LLM."""
        components = []
        for node in graph.nodes():
            node_data = graph.nodes[node]
            components.append({
                "name": node,
                "type": node_data.get("type", "Component"),
                "trust_zone": node_data.get("trust_zone", "Unknown"),
                "classification": node_data.get("classification", "Unclassified")
            })
        
        flows = []
        for u, v, data in graph.edges(data=True):
            flows.append({
                "source": u,
                "destination": v,
                "flow_type": data.get("flow_type", "Unknown"),
                "operation": data.get("operation", ""),
                "source_zone": graph.nodes[u].get("trust_zone", "Unknown"),
                "destination_zone": graph.nodes[v].get("trust_zone", "Unknown")
            })
        
        return {
            "components": components,
            "data_flows": flows,
            "trust_zones": ["Internet", "DMZ", "Trusted", "HighSide"]
        }
    
    def _build_threat_analysis_prompt(self, arch_description: Dict, typespec_source: str = None) -> str:
        """Build comprehensive threat analysis prompt for LLM."""
        prompt = f"""Analyze the following RAG (Retrieval-Augmented Generation) architecture for security threats.

**Architecture:**
```json
{json.dumps(arch_description, indent=2)}
```

**Focus Areas:**
1. **Trust Boundary Violations**: Data flowing from lower to higher trust zones
2. **AI-Specific Threats**:
   - Indirect prompt injection via retrieved context
   - Training data poisoning through vector store
   - Model inversion and data leakage
   - Context manipulation attacks
3. **Traditional Web/API Threats**: Injection, authentication, authorization
4. **Data Flow Integrity**: Validate each flow for confidentiality, integrity, availability

**Output Format:**
Return a JSON object with this structure:
{{
  "threats": [
    {{
      "threat_id": "LLM-001",
      "component": "component name",
      "severity": "Critical|High|Medium|Low",
      "description": "brief threat description",
      "attack_vector": "how the attack works",
      "mitigation": "recommended mitigation",
      "cwe_references": ["CWE-XX"]
    }}
  ]
}}

**Instructions:**
- Prioritize AI-specific threats (prompt injection, poisoning, leakage)
- Consider trust zone transitions carefully
- Focus on HIGH and CRITICAL severity threats
- Provide actionable mitigations
- Include CWE references where applicable
"""
        
        if typespec_source:
            prompt += f"\n**TypeSpec Source:**\n```typespec\n{typespec_source[:1000]}\n```\n"
        
        return prompt
    
    def _parse_llm_response(self, response_text: str) -> List[LLMThreatFinding]:
        """Parse LLM JSON response into threat findings."""
        try:
            data = json.loads(response_text)
            findings = []
            
            for threat in data.get("threats", []):
                findings.append(LLMThreatFinding(
                    threat_id=threat.get("threat_id", "LLM-UNKNOWN"),
                    component=threat.get("component", "Unknown"),
                    severity=threat.get("severity", "Medium"),
                    description=threat.get("description", ""),
                    attack_vector=threat.get("attack_vector", ""),
                    mitigation=threat.get("mitigation", ""),
                    cwe_references=threat.get("cwe_references", [])
                ))
            
            return findings
        except json.JSONDecodeError as e:
            print(f"Failed to parse LLM response: {e}")
            print(f"Response: {response_text[:500]}")
            return []


def get_llm_analyzer(api_key: Optional[str] = None) -> Optional[LLMThreatAnalyzer]:
    """
    Get LLM analyzer instance if available.
    
    Returns None if OpenAI is not configured (graceful degradation).
    """
    if not OPENAI_AVAILABLE:
        return None
    
    try:
        return LLMThreatAnalyzer(api_key=api_key)
    except (ValueError, ImportError):
        return None
